### ISSUE TITLE
log2pcap.py: scapy getmacbyip slow and requires root privileges on Linux

### ISSUE THREAD

**Issue by joesecurity** [droe/sslsplit#169]
* Requires root to run:

```
Traceback (most recent call last):
  File "log2pcap.py", line 225, in <module>
    netemu.add(logentry)
  File "log2pcap.py", line 189, in add
    self.connstate[conn5tuple].syn()
  File "log2pcap.py", line 90, in syn
    seq=self.src_seq)
  File "log2pcap.py", line 66, in _write_packet
    self._ctx.pcap.write(pkt)
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils.py", line 658, in write
    self._write_packet(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils.py", line 706, in _write_packet
    s = str(packet)
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 268, in __str__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 330, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 319, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 310, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 70, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 95, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 89, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 38, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/inet.py", line 732, in <lambda>
    conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 73, in getmacbyip
    nofilter=1)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 375, in srp1
    a,b=srp(*args,**kargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 357, in srp
    s = conf.L2socket(iface=iface, filter=filter, nofilter=nofilter, type=type)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 414, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 1] Operation not permitted
```

* Performance, for 2MB SSL split log file PCAP generation takes 30minutes. It seems like scapy _write_packet is the issue. Tested under scap 2.3.1.

**Comment by joesecurity** [comment]
It seem the issues are related and the root cause is the getmacbyip. When I override it the speed is acceptable:

`import scapy.layers.l2

def getmacbyip_n(ip, chainCC=0):
	return "11:22:33:44:55:66"

scapy.layers.l2.getmacbyip = getmacbyip_n`

**Comment by droe** [comment]
Thanks for the report!
